channel_ids: 1441609159136116788,1441609139250921553
github:
    enabled: true
    owner: x2sw-tw
    repo: mcalts-logger
    token: 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
last_log:
    '1441609139250921553': '1441625884443410494'
    '1441609159136116788': '1441640367987364044'
user_token: OTM3MzI5MzIxNTkxMzEyMzk0.GSbtY9.H1XKAH-FPTkcd6ybx-6HKkQ8pLXDOMZ8UcThuY
